export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'username': 'Benutzerkennung',
  'password': 'Passwort',
  'password.repeat': 'Passwort wiederholen',
  'register': 'Neu anmelden',
  'back': 'Zurück',
  'email': 'E-Mail-Adresse',
  'fullname': 'Vollständiger Name',
  'create.user': 'Nutzer anlegen',
  'fachref': 'Fachref-Assistent',
  'fachref.short': 'Instrumente zum Bestandsmanagement.',
  'protokoll': 'Ausleihprotokoll',
  'protokoll.short': 'Dashboard zur Detailanalyse eines Titels.',
  'admin': 'Administration',
  'admin.short': 'Einstellungen und Nutzer verwalten.',
  'media': 'Medien-Management',
  'media.short': 'Verwaltung von SUSHI-Accounts etc.',
  'duepublica': 'DuE-PublicA',
  'duepublica.short': 'Das Bibliometrie-Tool.',
  'settings': 'Eigene Einstellungen',
  'settings.short': 'Eine Reihe an eigenen Einstellungen',
  'error.noMatchingPasswords.summary': 'Passwörter nicht identisch.',
  'error.noMatchingPasswords.detail': 'Die eingegebenen Passwörter stimmen nicht überein. Bitte erneut eingeben.',
  'error.noUsername.summary': 'Keine Nutzerkennung.',
  'error.noUsername.detail': 'Bitte einen Nutzernamen wählen.',
  'error.register.summary': 'Nutzername bereits vergeben.',
  'error.register.detail': 'Bitte einen anderen Nutzernamen wählen.',
  'error.login.summary': 'Anmeldung fehlgeschlagen.',
  'error.login.detail': 'Bitte Nutzerkennung und Passwort prüfen.',
  'error.noPassword.summary': 'Kein Passwort.',
  'error.noPassword.detail': 'Bitte ein Passwort eingeben.',
  'logout.success': 'Sie haben sich erfolgreich abgemeldet. Vielen Dank für Ihren Besuch.',
  'to.login': 'zur Anmeldeseite',
  'good.bye': 'Auf Wiedersehen',
  'data.protection': 'Datenschutzhinweis',
  'data.protection.text': 'Wenn Sie die Dienste der Lib-Intel-Plattform nutzen, werden die von Ihnen eingegeben Daten ' +
  'an uns übermittelt und gespeichert. Zur Verbeserung der Dienste speichern wir zusätzlich Daten über die Anfragen. ' +
  'Im Rahmen der Auftragsverarbeitung im ELi:SA-Kontext werden Ihre Daten an das Hochschulbibliothekszentrum (hbz) ' +
  'NRW weitergegeben. Die Daten werden dort ausschließlich für die Verarbeitung der Bestellung verwendet.',
  'data.protection.link': 'mehr zum Datenschutz an der UB',
  'to.protokoll': 'zum Ausleihprotokoll',
  'to.settings': 'zu den Einstellungen',
  'to.fachref': 'zum Fachref-Assistenten',
  'to.admin': 'zur Administration',
  'to.media': 'zum Medien-Management',
  'to.bibliometrics': 'zu DuEPublicA',
  'personal.settings': 'Persönliche Einstellungen',
  'elisa.account': 'ELi:SA-Account',
  'save': 'Speichern',
};
