export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'username': 'Benutzerkennung',
  'password': 'Passwort',
  'password.repeat': 'Passwort wiederholen',
  'register': 'Neu anmelden',
  'back': 'Zurück',
  'email': 'E-Mail-Adresse',
  'fullname': 'Vollständiger Name',
  'create.user': 'Nutzer anlegen',
  'fachref': 'Fachref-Assistent',
  'fachref.short': 'Instrumente zum Bestandsmanagement.',
  'protokoll': 'Ausleihprotokoll',
  'protokoll.short': 'Dashboard zur Detailanalyse eines Titels.',
  'admin': 'Administration',
  'admin.short': 'Einstellungen und Nutzer verwalten.',
  'media': 'Medien-Management',
  'media.short': 'Verwaltung von SUSHI-Accounts etc.',
  'duepublica': 'DuE-PublicA',
  'duepublica.short': 'Das Bibliometrie-Tool.',
  'settings': 'Eigene Einstellungen',
  'settings.short': 'Eine Reihe an eigenen Einstellungen',
  'error.noMatchingPasswords.summary': 'Passwörter nicht identisch.',
  'error.noMatchingPasswords.detail': 'Die eingegebenen Passwörter stimmen nicht überein. Bitte erneut eingeben.',
  'error.noUsername.summary': 'Keine Nutzerkennung.',
  'error.noUsername.detail': 'Bitte einen Nutzernamen wählen.',
  'error.register.summary': 'Nutzername bereits vergeben.',
  'error.register.detail': 'Bitte einen anderen Nutzernamen wählen.',
  'error.login.summary': 'Anmeldung fehlgeschlagen.',
  'error.login.detail': 'Bitte Nutzerkennung und Passwort prüfen.',
  'error.noPassword.summary': 'Kein Passwort.',
  'error.noPassword.detail': 'Bitte ein Passwort eingeben.',
};
